//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Web_VLR.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Player
    {
        [Display(Name = "#")]
        public int ID { get; set; }
        [Display(Name = "Tag del jugador")]
        public string TagName { get; set; }

        [Display(Name = "Equipo actual del jugador")]
        public string Equipo { get; set; }
        [Display(Name = "Estatus del jugador")]
        public string Estado { get; set; }
        [Display(Name = "Juego del jugador")]
        public string Juego { get; set; }
    

    }
}



